name: Run API Tests

on:
  workflow_dispatch: # Manual trigger button only

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -D @playwright/test
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Run API tests
        run: |
          echo "Running API tests from getArticlesApi.spec.ts"
          mkdir -p playwright-report
          npx playwright test tests/TestWithMethods/getArticlesApi.spec.ts --reporter=html
          ls -la playwright-report
        
      - name: Upload test results
        if: always() # Upload results even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_number }}
          path: playwright-report
          retention-days: 30

      - name: Print test summary
        if: always()
        run: |
          echo "Test Run Completed"
          echo "Check the playwright-report artifact for detailed results"