name: UI Tests

on:
  workflow_dispatch: # Manual trigger button only

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright and browsers
        run: |
          npx playwright install --with-deps
        
      - name: Run UI tests
        env:
          CI: true
        run: |
          echo "Running UI tests from conduitWithMethods.spec.ts"
          npx playwright test tests/TestWithMethods/conduitWithMethods.spec.ts --reporter=html --max-failures=5
          
      - name: Check test results
        if: always()
        run: |
          if [ -d "playwright-report" ]; then
            echo "Test report generated successfully"
            ls -la playwright-report
          else
            echo "No test report found"
            exit 1
          fi
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-ui-${{ github.run_number }}
          path: playwright-report
          retention-days: 30

      - name: Upload test screenshots and videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: test-results
          retention-days: 30